config/routes.rb
Rails.application.routes.draw do
  root to: 'devices#index'
  resource :devices, only: :new
  resource :ios, only: :none do
    collection do
      get :send_notify
      post :push_notify
    end
  end
  resource :android, only: :none do
    collection do
      get :send_notify
      post :push_notify
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
end

app/controllers/androids_controller.rb
require 'gcm'

class AndroidsController < ApplicationController
  def send_notify
  end
  
  def push_notify
    gcm = GCM.new('AIzaSyAXmqAL_Y9Zrugd8DDo6o4QnEZZ9nLEkbE')
    response = gcm.send_with_notification_key(params[:token], {data: {message: params[:message]}})
    redirect_to send_notify_android_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @devices = Device.all
  end
  
  def new
    device = Device.new(token: params[:token], platform: params[:platform])
    device.save
    head :ok
  end
end

app/controllers/ios_controller.rb
require 'houston'

class IosController < ApplicationController
  def send_notify
  end
  
  def push_notify
    apn = Houston::Client.production if Rails.env.production?
    apn = Houston::Client.development if Rails.env.development?
      
    apn.certificate = File.read(File.join(Rails.root, 'public','ck.pem'))
    apn.passphrase = '1234'
    
    token = params[:token]
    
    notification = Houston::Notification.new(device: token)
    notification.alert = params[:messeage]
    
    notification.badge = 57
    notification.sound = 'sosumi.aiff'
    notification.category = 'INVITE_CATEGORY'
    notification.content_available = true
    notification.mutable_content = true
    notification.custom_data = { foo: 'bar' }
    
    apn.push(notification)
    redirect_to root_path
  end
end

app/helpers/androids_helper.rb
module AndroidsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/ios_helper.rb
module IosHelper
end

app/views/androids/send_notify.html.erb
<%= form_tag push_notify_android_path, method: 'post' do %>
  Token: <%= text_field_tag :token %>
  <br>
  Message: <%= text_area_tag :message %>
  <br>
  <%= submit_tag('Submit') %>
<% end %>
<%= link_to 'Home', root_path %>

app/views/devices/_device.html.erb
<tr>
  <td><%= device.token %></td>
  <td><%= device.platform %></td>
  <td><%= device.created_at %></td>
</tr>

app/views/devices/index.html.erb
<table style="width:100%">
  <tr>
    <td>Token</td>
    <td>Platform</td>
    <td>Created At</td>
  </tr>
  <%= render partial: 'device', collection: @devices %>
</table>
<%= link_to 'IOS Notification', send_notify_ios_path %>
<br>
<%= link_to 'ANDROID Notification', send_notify_android_path %>

app/views/ios/send_notify.html.erb
<%= form_tag push_notify_ios_path, method: 'post' do %>
  Token: <%= text_field_tag :token %>
  <br>
  Message: <%= text_area_tag :messeage %>
  <br>
  <%= submit_tag('Submit') %>
<% end %>
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PushNotify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>